### ISSUE TITLE
Any chance of you making a Stremio addon for this?

### ISSUE THREAD

**Issue by igorcafe** [LucCADORET/comeover#4]

**Comment by LucCADORET** [comment]
Could you be more precise ? Stremio seems to be some kind of nice library for your own files, right ? How do you think it could fit in comeover ? For info, I don't plan on giving direct links to files from comeover, as I don't want to be accountable for any illegal use of the website.

**Comment by igorcafe** [comment]
[Stremio](https://www.stremio.com/) is more like a peer-to-peer streaming application.
It can mainly streams torrents, but also some other contents like Youtube videos and so on.

Adding ComeOver features as an addon to Stremio would make it the perfect app to watch TV shows with friends.
Stremio is not "illegal" by itself, if you don't use community extensions to watch restrict content.

**Comment by igorcafe** [comment]
There is actually a website for that, peario.xyz
