### ISSUE TITLE
Replace dead trackers with working ones and fix tracker format

### ISSUE THREAD

**Issue by Glenta** [LucCADORET/comeover#8]
When using the magnet link and .torrent feature, it seems that `/announce` is missing from the `udp://` trackers. Additionally, `udp://tracker.coppersurfer.tk:6969` is now a dead tracker that had shutdown long ago, it would be best to use trackers from [ngosang's best trackers list](https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt). 

Here are also some WebSocket trackers you can use:
`wss://tracker.webtorrent.dev`
`wss://tracker.files.fm:7073/announce`
`ws://tracker.files.fm:7072/announce`

One last note, when clicking on either Magnet URI or Download .torrent under Torrent info, `unsafe:` is added in front of it. And for Download .torrent, it downloads a file without the extension .torrent added to the end.

**Comment by LucCADORET** [comment]
That's true, I also noticed dead trackers. It actually prevents the website to work properly. Will try to address this in the coming days.

**Comment by LucCADORET** [comment]
I removed the unsafe: from the URL, and added `wss://tracker.webtorrent.dev` as the sole tracker. Maybe should use a list in the future. As a side note, I can't get the website working properly, I think it's simply because of the communication between Comeover clients don't go through.
